version: "3.7"

services:
  test-server:
    container_name: sams-webhook-test-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
